# Site
repository: TheRijn/website
favicon: images/favicon.ico

# Personal info
name: Marijn Doeve
title: Student Informatica en Studentassistent bij Minor programmeren
email: marijn@doeve.me
# website: jansenmarijn.nl

# Social links
twitter_username: marijn100
github_username:  TheRijn
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: marijn100
linkedin_username: marijndoeve
# pinterest_username: jekyll
# youtube_username: globalmtb

# About Section
about_title: Over mij
about_profile_image: images/marijn.jpg
about_content: | # this will include new lines to allow paragraphs
  Een volledige versie van mijn CV is  [hier](https://github.com/TheRijn/CV/raw/master/main.pdf) te vinden.

# Projects Section
projects_title: Projecten

# Experience Section
experience_title: Ervaringen

# Education Section
educaton_title: Opleidingen

# More Section
# more_title: Meer over mij
# more_content: | # this will include new lines to allow paragraphs
#   Daarnaast zijn mijn hobbies:
#     - Solderen
#     - Snowboarden

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

darkmode: false
