# Site
repository: TheRijn/website
favicon: images/favicon.ico

# Personal info
name: Marijn Doeve
title: Student Informatica en Studentassistent bij Minor programmeren
email: marijn@doeve.me
# website: marijndoeve.nl

# Social links
twitter_username: marijn100
github_username: TheRijn
stackoverflow_username: "4734846"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: marijn100
linkedin_username: marijndoeve
# pinterest_username: jekyll
# youtube_username: globalmtb

# About Section
about_title: Over mij
about_profile_image: images/marijn.jpg
about_content: | # this will include new lines to allow paragraphs
  Hoi! Ik ben Marijn all-round nerd en student Informatica. Ik heb mijn bachelor bijna
  afgerond, maar ben voor nu eerst opzoek naar een leuke baan.

  Ik heb veel ervaring met Python
  en Swift, maar vind het ook erg leuk om iets nieuws te leren.

# Projects Section
projects_title: Projecten

# Experience Section
experience_title: Ervaringen

# Education Section
education_title: Opleidingen

# More Section
# more_title: Meer over mij
# more_content: | # this will include new lines to allow paragraphs
#   Daarnaast zijn mijn hobbies:
#     - Solderen
#     - Snowboarden
more_title: Programmeertalen en Frameworks
more_content: |
  Een selectie van de programmeertalen en framworks waar ik door de jaren heen mee
  gewerkt heb. De meeste ervaring heb ik met de __dikgedrukte__ items

  Android, Arduino, Bash, __C__, C#, C++, CSS, __Django__, __Docker__, ESP32, Flask, Git, Go, Haskell, HTML, Java, JavaScript, Jinja, LaTeX, Linux, macOS, Nginx, pfSense, PHP, PostgreSQL, Prolog, Pug, __Python__, Sass, Scratch, SQL, __Swift__, SwiftUI, Treafik, TypeScript , Ubuntu, UIKit, Unity, Vue.js

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag

darkmode: false
